// <auto-generated />
using Forms_Ver01.App.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Alura.Filmes.App.Migrations
{
    [DbContext(typeof(CodigosContexto))]
    partial class CodigosContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Forms_Ver01.App.Negocio.Codigos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Conta_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnName("Codigo")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Servico")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Ultima Alteracao")
                        .HasColumnType("datetime");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnName("Usuario")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Codigos");
                });
#pragma warning restore 612, 618
        }
    }
}
